### ISSUE TITLE
Consider being virtual dom agnostic.

### ISSUE THREAD

**Issue by DylanPiercey** [jkroso/rill-render-errors#1]
Hey I like the idea for this middleware but for myself (running it in the browser as well as the server) having two vdoms (react and mana) seems like a little much.

I was thinking it would be cool if this module injected html on the server side and perhaps used the native dom in the browser?

For an example of injecting into html you can check out https://github.com/rill-js/session/blob/master/server/index.js#L46.

Unrelated: It would be sweet to get a mana rendering middleware similar to https://github.com/rill-js/react 😉.

**Comment by jkroso** [comment]
I could make the `JSX` function a parameter and rely on rill-js/react style middleware for serialization. 

One thing I find weird about that middleware though is that it automatically renders into the DOM on the client side. Rather than return a react element like I would expect. It would interesting to see it in use though.

**Comment by DylanPiercey** [comment]
@jkroso the main reason middleware such as `rill-js/progress` directly injects itself into the DOM its to lighten the cognitive burden and is an attempt at keeping with the "middleware to solve your problems" ideology that is in place for other middleware. I'm currently trying to find a balance though as there are situations where this isn't ideal; Currently trying to figure out a way to implement toasts/alerts in a clean Isomorphic way but I am currently doing as you said.

In the future I'd like to have simple things that are often needed for sites that are page agnostic like modals, alerts, loaders, notifications and menus be easily pluggable into apps and I'm still trying to figure out the best way to encourage such an environment.

For the core middleware I'd just like to make it vdom agnostic as I think that react holds a bit of a monopoly and I'd rather not promote that.
